// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: skald/relay/v2/relay_frame.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// NORMATIVE schema for the Skald Relay v2 transport.
// Mirror copy of data/iOS-app/v2/relay-protocol.md §2.
// Do NOT edit field numbers / names — clients and servers depend on byte
// compatibility.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Skald_Relay_V2_Status: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case online // = 1
  case offline // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .online
    case 2: self = .offline
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .online: return 1
    case .offline: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Skald_Relay_V2_Status] = [
    .unspecified,
    .online,
    .offline,
  ]

}

nonisolated enum Skald_Relay_V2_Platform: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case ios // = 1
  case android // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ios
    case 2: self = .android
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ios: return 1
    case .android: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Skald_Relay_V2_Platform] = [
    .unspecified,
    .ios,
    .android,
  ]

}

nonisolated struct Skald_Relay_V2_RelayFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var frame: Skald_Relay_V2_RelayFrame.OneOf_Frame? = nil

  var challenge: Skald_Relay_V2_Challenge {
    get {
      if case .challenge(let v)? = frame {return v}
      return Skald_Relay_V2_Challenge()
    }
    set {frame = .challenge(newValue)}
  }

  var auth: Skald_Relay_V2_Auth {
    get {
      if case .auth(let v)? = frame {return v}
      return Skald_Relay_V2_Auth()
    }
    set {frame = .auth(newValue)}
  }

  var authOk: Skald_Relay_V2_AuthOk {
    get {
      if case .authOk(let v)? = frame {return v}
      return Skald_Relay_V2_AuthOk()
    }
    set {frame = .authOk(newValue)}
  }

  var authError: Skald_Relay_V2_AuthError {
    get {
      if case .authError(let v)? = frame {return v}
      return Skald_Relay_V2_AuthError()
    }
    set {frame = .authError(newValue)}
  }

  var authorize: Skald_Relay_V2_Authorize {
    get {
      if case .authorize(let v)? = frame {return v}
      return Skald_Relay_V2_Authorize()
    }
    set {frame = .authorize(newValue)}
  }

  var authorizeOk: Skald_Relay_V2_AuthorizeOk {
    get {
      if case .authorizeOk(let v)? = frame {return v}
      return Skald_Relay_V2_AuthorizeOk()
    }
    set {frame = .authorizeOk(newValue)}
  }

  var pairingStart: Skald_Relay_V2_PairingStart {
    get {
      if case .pairingStart(let v)? = frame {return v}
      return Skald_Relay_V2_PairingStart()
    }
    set {frame = .pairingStart(newValue)}
  }

  var pairingReady: Skald_Relay_V2_PairingReady {
    get {
      if case .pairingReady(let v)? = frame {return v}
      return Skald_Relay_V2_PairingReady()
    }
    set {frame = .pairingReady(newValue)}
  }

  var pairingStop: Skald_Relay_V2_PairingStop {
    get {
      if case .pairingStop(let v)? = frame {return v}
      return Skald_Relay_V2_PairingStop()
    }
    set {frame = .pairingStop(newValue)}
  }

  var pairingStopOk: Skald_Relay_V2_PairingStopOk {
    get {
      if case .pairingStopOk(let v)? = frame {return v}
      return Skald_Relay_V2_PairingStopOk()
    }
    set {frame = .pairingStopOk(newValue)}
  }

  var clientPaired: Skald_Relay_V2_ClientPaired {
    get {
      if case .clientPaired(let v)? = frame {return v}
      return Skald_Relay_V2_ClientPaired()
    }
    set {frame = .clientPaired(newValue)}
  }

  var message: Skald_Relay_V2_Message {
    get {
      if case .message(let v)? = frame {return v}
      return Skald_Relay_V2_Message()
    }
    set {frame = .message(newValue)}
  }

  var peerOffline: Skald_Relay_V2_PeerOffline {
    get {
      if case .peerOffline(let v)? = frame {return v}
      return Skald_Relay_V2_PeerOffline()
    }
    set {frame = .peerOffline(newValue)}
  }

  var presenceRequest: Skald_Relay_V2_PresenceRequest {
    get {
      if case .presenceRequest(let v)? = frame {return v}
      return Skald_Relay_V2_PresenceRequest()
    }
    set {frame = .presenceRequest(newValue)}
  }

  var presenceList: Skald_Relay_V2_PresenceList {
    get {
      if case .presenceList(let v)? = frame {return v}
      return Skald_Relay_V2_PresenceList()
    }
    set {frame = .presenceList(newValue)}
  }

  var presenceEvent: Skald_Relay_V2_PresenceEvent {
    get {
      if case .presenceEvent(let v)? = frame {return v}
      return Skald_Relay_V2_PresenceEvent()
    }
    set {frame = .presenceEvent(newValue)}
  }

  var error: Skald_Relay_V2_Error {
    get {
      if case .error(let v)? = frame {return v}
      return Skald_Relay_V2_Error()
    }
    set {frame = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Frame: Equatable, Sendable {
    case challenge(Skald_Relay_V2_Challenge)
    case auth(Skald_Relay_V2_Auth)
    case authOk(Skald_Relay_V2_AuthOk)
    case authError(Skald_Relay_V2_AuthError)
    case authorize(Skald_Relay_V2_Authorize)
    case authorizeOk(Skald_Relay_V2_AuthorizeOk)
    case pairingStart(Skald_Relay_V2_PairingStart)
    case pairingReady(Skald_Relay_V2_PairingReady)
    case pairingStop(Skald_Relay_V2_PairingStop)
    case pairingStopOk(Skald_Relay_V2_PairingStopOk)
    case clientPaired(Skald_Relay_V2_ClientPaired)
    case message(Skald_Relay_V2_Message)
    case peerOffline(Skald_Relay_V2_PeerOffline)
    case presenceRequest(Skald_Relay_V2_PresenceRequest)
    case presenceList(Skald_Relay_V2_PresenceList)
    case presenceEvent(Skald_Relay_V2_PresenceEvent)
    case error(Skald_Relay_V2_Error)

  }

  init() {}
}

nonisolated struct Skald_Relay_V2_Message: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ciphertext: Data = Data()

  var nonce: Data = Data()

  var peer: Data = Data()

  var live: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PeerOffline: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var peer: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PresenceRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PresenceList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var online: [Data] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PresenceEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pubkey: Data = Data()

  var status: Skald_Relay_V2_Status = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_Challenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nonce: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_Auth: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var role: Skald_Relay_V2_Auth.OneOf_Role? = nil

  var agent: Skald_Relay_V2_AuthAgent {
    get {
      if case .agent(let v)? = role {return v}
      return Skald_Relay_V2_AuthAgent()
    }
    set {role = .agent(newValue)}
  }

  var client: Skald_Relay_V2_AuthClient {
    get {
      if case .client(let v)? = role {return v}
      return Skald_Relay_V2_AuthClient()
    }
    set {role = .client(newValue)}
  }

  var pairing: Skald_Relay_V2_AuthPairing {
    get {
      if case .pairing(let v)? = role {return v}
      return Skald_Relay_V2_AuthPairing()
    }
    set {role = .pairing(newValue)}
  }

  var signature: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Role: Equatable, Sendable {
    case agent(Skald_Relay_V2_AuthAgent)
    case client(Skald_Relay_V2_AuthClient)
    case pairing(Skald_Relay_V2_AuthPairing)

  }

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthAgent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var agentEd25519Pub: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthClient: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var namespaceID: Data = Data()

  var clientEd25519Pub: Data = Data()

  var deviceToken: String = String()

  var platform: Skald_Relay_V2_Platform = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthPairing: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var namespaceID: Data = Data()

  var clientEd25519Pub: Data = Data()

  var clientX25519Pub: Data = Data()

  var pairingToken: Data = Data()

  var deviceToken: String = String()

  var platform: Skald_Relay_V2_Platform = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthOk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var namespaceID: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: String = String()

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_Authorize: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var clients: [Data] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_AuthorizeOk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var authorized: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PairingStart: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pairingToken: Data = Data()

  var ttl: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PairingReady: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ttl: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PairingStop: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_PairingStopOk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_ClientPaired: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var clientEd25519Pub: Data = Data()

  var clientX25519Pub: Data = Data()

  var platform: Skald_Relay_V2_Platform = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Skald_Relay_V2_Error: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: String = String()

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "skald.relay.v2"

nonisolated extension Skald_Relay_V2_Status: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATUS_UNSPECIFIED\0\u{1}STATUS_ONLINE\0\u{1}STATUS_OFFLINE\0")
}

nonisolated extension Skald_Relay_V2_Platform: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLATFORM_UNSPECIFIED\0\u{1}PLATFORM_IOS\0\u{1}PLATFORM_ANDROID\0")
}

nonisolated extension Skald_Relay_V2_RelayFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RelayFrame"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}challenge\0\u{1}auth\0\u{3}auth_ok\0\u{3}auth_error\0\u{1}authorize\0\u{3}authorize_ok\0\u{3}pairing_start\0\u{3}pairing_ready\0\u{3}pairing_stop\0\u{3}pairing_stop_ok\0\u{3}client_paired\0\u{1}message\0\u{3}peer_offline\0\u{3}presence_request\0\u{3}presence_list\0\u{3}presence_event\0\u{1}error\0\u{c}\u{12}\u{1}\u{c}\u{13}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Skald_Relay_V2_Challenge?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .challenge(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .challenge(v)
        }
      }()
      case 2: try {
        var v: Skald_Relay_V2_Auth?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .auth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .auth(v)
        }
      }()
      case 3: try {
        var v: Skald_Relay_V2_AuthOk?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .authOk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .authOk(v)
        }
      }()
      case 4: try {
        var v: Skald_Relay_V2_AuthError?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .authError(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .authError(v)
        }
      }()
      case 5: try {
        var v: Skald_Relay_V2_Authorize?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .authorize(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .authorize(v)
        }
      }()
      case 6: try {
        var v: Skald_Relay_V2_AuthorizeOk?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .authorizeOk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .authorizeOk(v)
        }
      }()
      case 7: try {
        var v: Skald_Relay_V2_PairingStart?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .pairingStart(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .pairingStart(v)
        }
      }()
      case 8: try {
        var v: Skald_Relay_V2_PairingReady?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .pairingReady(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .pairingReady(v)
        }
      }()
      case 9: try {
        var v: Skald_Relay_V2_PairingStop?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .pairingStop(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .pairingStop(v)
        }
      }()
      case 10: try {
        var v: Skald_Relay_V2_PairingStopOk?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .pairingStopOk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .pairingStopOk(v)
        }
      }()
      case 11: try {
        var v: Skald_Relay_V2_ClientPaired?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .clientPaired(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .clientPaired(v)
        }
      }()
      case 12: try {
        var v: Skald_Relay_V2_Message?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .message(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .message(v)
        }
      }()
      case 13: try {
        var v: Skald_Relay_V2_PeerOffline?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .peerOffline(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .peerOffline(v)
        }
      }()
      case 14: try {
        var v: Skald_Relay_V2_PresenceRequest?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .presenceRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .presenceRequest(v)
        }
      }()
      case 15: try {
        var v: Skald_Relay_V2_PresenceList?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .presenceList(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .presenceList(v)
        }
      }()
      case 16: try {
        var v: Skald_Relay_V2_PresenceEvent?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .presenceEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .presenceEvent(v)
        }
      }()
      case 17: try {
        var v: Skald_Relay_V2_Error?
        var hadOneofValue = false
        if let current = self.frame {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.frame = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.frame {
    case .challenge?: try {
      guard case .challenge(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .auth?: try {
      guard case .auth(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .authOk?: try {
      guard case .authOk(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .authError?: try {
      guard case .authError(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .authorize?: try {
      guard case .authorize(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .authorizeOk?: try {
      guard case .authorizeOk(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .pairingStart?: try {
      guard case .pairingStart(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .pairingReady?: try {
      guard case .pairingReady(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .pairingStop?: try {
      guard case .pairingStop(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .pairingStopOk?: try {
      guard case .pairingStopOk(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .clientPaired?: try {
      guard case .clientPaired(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .message?: try {
      guard case .message(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .peerOffline?: try {
      guard case .peerOffline(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .presenceRequest?: try {
      guard case .presenceRequest(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .presenceList?: try {
      guard case .presenceList(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    }()
    case .presenceEvent?: try {
      guard case .presenceEvent(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    }()
    case .error?: try {
      guard case .error(let v)? = self.frame else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_RelayFrame, rhs: Skald_Relay_V2_RelayFrame) -> Bool {
    if lhs.frame != rhs.frame {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_Message: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Message"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ciphertext\0\u{1}nonce\0\u{1}peer\0\u{1}live\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.peer) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.live) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 1)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 2)
    }
    if !self.peer.isEmpty {
      try visitor.visitSingularBytesField(value: self.peer, fieldNumber: 3)
    }
    if self.live != false {
      try visitor.visitSingularBoolField(value: self.live, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_Message, rhs: Skald_Relay_V2_Message) -> Bool {
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.peer != rhs.peer {return false}
    if lhs.live != rhs.live {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PeerOffline: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PeerOffline"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}peer\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.peer) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.peer.isEmpty {
      try visitor.visitSingularBytesField(value: self.peer, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PeerOffline, rhs: Skald_Relay_V2_PeerOffline) -> Bool {
    if lhs.peer != rhs.peer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PresenceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PresenceRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PresenceRequest, rhs: Skald_Relay_V2_PresenceRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PresenceList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PresenceList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}online\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.online) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.online.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.online, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PresenceList, rhs: Skald_Relay_V2_PresenceList) -> Bool {
    if lhs.online != rhs.online {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PresenceEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PresenceEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pubkey\0\u{1}status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.pubkey) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pubkey.isEmpty {
      try visitor.visitSingularBytesField(value: self.pubkey, fieldNumber: 1)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PresenceEvent, rhs: Skald_Relay_V2_PresenceEvent) -> Bool {
    if lhs.pubkey != rhs.pubkey {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_Challenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Challenge"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nonce\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_Challenge, rhs: Skald_Relay_V2_Challenge) -> Bool {
    if lhs.nonce != rhs.nonce {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_Auth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Auth"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}agent\0\u{1}client\0\u{1}pairing\0\u{1}signature\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Skald_Relay_V2_AuthAgent?
        var hadOneofValue = false
        if let current = self.role {
          hadOneofValue = true
          if case .agent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.role = .agent(v)
        }
      }()
      case 2: try {
        var v: Skald_Relay_V2_AuthClient?
        var hadOneofValue = false
        if let current = self.role {
          hadOneofValue = true
          if case .client(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.role = .client(v)
        }
      }()
      case 3: try {
        var v: Skald_Relay_V2_AuthPairing?
        var hadOneofValue = false
        if let current = self.role {
          hadOneofValue = true
          if case .pairing(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.role = .pairing(v)
        }
      }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.role {
    case .agent?: try {
      guard case .agent(let v)? = self.role else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .client?: try {
      guard case .client(let v)? = self.role else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .pairing?: try {
      guard case .pairing(let v)? = self.role else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_Auth, rhs: Skald_Relay_V2_Auth) -> Bool {
    if lhs.role != rhs.role {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthAgent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthAgent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}agent_ed25519_pub\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.agentEd25519Pub) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.agentEd25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.agentEd25519Pub, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthAgent, rhs: Skald_Relay_V2_AuthAgent) -> Bool {
    if lhs.agentEd25519Pub != rhs.agentEd25519Pub {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthClient: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthClient"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}namespace_id\0\u{3}client_ed25519_pub\0\u{3}device_token\0\u{1}platform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.namespaceID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.clientEd25519Pub) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceToken) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.platform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.namespaceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.namespaceID, fieldNumber: 1)
    }
    if !self.clientEd25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientEd25519Pub, fieldNumber: 2)
    }
    if !self.deviceToken.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceToken, fieldNumber: 3)
    }
    if self.platform != .unspecified {
      try visitor.visitSingularEnumField(value: self.platform, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthClient, rhs: Skald_Relay_V2_AuthClient) -> Bool {
    if lhs.namespaceID != rhs.namespaceID {return false}
    if lhs.clientEd25519Pub != rhs.clientEd25519Pub {return false}
    if lhs.deviceToken != rhs.deviceToken {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthPairing: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthPairing"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}namespace_id\0\u{3}client_ed25519_pub\0\u{3}client_x25519_pub\0\u{3}pairing_token\0\u{3}device_token\0\u{1}platform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.namespaceID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.clientEd25519Pub) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.clientX25519Pub) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.pairingToken) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.deviceToken) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.platform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.namespaceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.namespaceID, fieldNumber: 1)
    }
    if !self.clientEd25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientEd25519Pub, fieldNumber: 2)
    }
    if !self.clientX25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientX25519Pub, fieldNumber: 3)
    }
    if !self.pairingToken.isEmpty {
      try visitor.visitSingularBytesField(value: self.pairingToken, fieldNumber: 4)
    }
    if !self.deviceToken.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceToken, fieldNumber: 5)
    }
    if self.platform != .unspecified {
      try visitor.visitSingularEnumField(value: self.platform, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthPairing, rhs: Skald_Relay_V2_AuthPairing) -> Bool {
    if lhs.namespaceID != rhs.namespaceID {return false}
    if lhs.clientEd25519Pub != rhs.clientEd25519Pub {return false}
    if lhs.clientX25519Pub != rhs.clientX25519Pub {return false}
    if lhs.pairingToken != rhs.pairingToken {return false}
    if lhs.deviceToken != rhs.deviceToken {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthOk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthOk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}namespace_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.namespaceID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.namespaceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.namespaceID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthOk, rhs: Skald_Relay_V2_AuthOk) -> Bool {
    if lhs.namespaceID != rhs.namespaceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthError, rhs: Skald_Relay_V2_AuthError) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_Authorize: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Authorize"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}clients\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.clients) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clients.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.clients, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_Authorize, rhs: Skald_Relay_V2_Authorize) -> Bool {
    if lhs.clients != rhs.clients {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_AuthorizeOk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthorizeOk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}authorized\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.authorized) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.authorized != 0 {
      try visitor.visitSingularUInt32Field(value: self.authorized, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_AuthorizeOk, rhs: Skald_Relay_V2_AuthorizeOk) -> Bool {
    if lhs.authorized != rhs.authorized {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PairingStart: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingStart"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pairing_token\0\u{1}ttl\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.pairingToken) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.ttl) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pairingToken.isEmpty {
      try visitor.visitSingularBytesField(value: self.pairingToken, fieldNumber: 1)
    }
    if self.ttl != 0 {
      try visitor.visitSingularUInt32Field(value: self.ttl, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PairingStart, rhs: Skald_Relay_V2_PairingStart) -> Bool {
    if lhs.pairingToken != rhs.pairingToken {return false}
    if lhs.ttl != rhs.ttl {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PairingReady: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingReady"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ttl\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.ttl) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ttl != 0 {
      try visitor.visitSingularUInt32Field(value: self.ttl, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PairingReady, rhs: Skald_Relay_V2_PairingReady) -> Bool {
    if lhs.ttl != rhs.ttl {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PairingStop: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingStop"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PairingStop, rhs: Skald_Relay_V2_PairingStop) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_PairingStopOk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingStopOk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_PairingStopOk, rhs: Skald_Relay_V2_PairingStopOk) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_ClientPaired: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ClientPaired"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_ed25519_pub\0\u{3}client_x25519_pub\0\u{1}platform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.clientEd25519Pub) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.clientX25519Pub) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.platform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientEd25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientEd25519Pub, fieldNumber: 1)
    }
    if !self.clientX25519Pub.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientX25519Pub, fieldNumber: 2)
    }
    if self.platform != .unspecified {
      try visitor.visitSingularEnumField(value: self.platform, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_ClientPaired, rhs: Skald_Relay_V2_ClientPaired) -> Bool {
    if lhs.clientEd25519Pub != rhs.clientEd25519Pub {return false}
    if lhs.clientX25519Pub != rhs.clientX25519Pub {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Skald_Relay_V2_Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Error"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Skald_Relay_V2_Error, rhs: Skald_Relay_V2_Error) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
